# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FlaiQgisPlugin
                                 A QGIS plugin
 Provides GUI access to Flai's Open Lidar Data Hub and local control over the Flai CLI for AI-powered geospatial classification.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-11
        copyright            : (C) 2025 by Flai d.o.o
        email                : vid.tk@flai.ai
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FlaiQgisPlugin class from file FlaiQgisPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .flai_qgis_plugin import FlaiQgisPlugin
    return FlaiQgisPlugin(iface)
