# messages
TIMEOUT_ERROR = "Timeout error occured, experience might be degraded." 
GENERAL_ERROR = "Unforseeable error occured: "

OUTPUT_PATH_MANAGER_DEFAULT_VALUE_MESSAGE = "Output paths have been automatically generated, no need to select them."


# path related
MAIN_SAVING_FOLDER_NAME = 'flai-utils'

CLI_FOLDER_NAME = 'cli'
CLI_PROCESSED_DATA_FOLDER_NAME = 'outputs'

DATAHUB_FOLDER_NAME = 'datahub'
DATAHUB_DATASET_SAVED_SCHEME_FILE = 'dataset.metadata'

HIDDEN_SETTINGS_FILE_NAME = '.settings.ini'
HIDDEN_FLAI_CONFIG_FILE_NAME = '.flai'


# programmable variables
DATETIME_PLACEHOLDER = 'current-date/current-time'

TIMEOUT_TIME_IN_SECONDS = 15

OUTPUT_FOLDER_WATCHER_POOLING_RATE_IN_SEC = 0.2

AVAILABLE_REGIONS_COLOR = "#7e4b00"

SEMANTIC_DEFINITION_VALUE_FIELD = 'code'
SEMANTIC_DEFINITION_LABEL_FIELD = 'name'
SEMANTIC_DEFINITION_COLOR_FIELD = 'color'

POSSIBLE_NODE_KEY_SCHEMA_ID = 'out_semantic_definition_schema_id'
POSSIBLE_NODE_KEY_MODEL_ID  = 'ai_model_id'


# system related
SYSTEM_MACOS   = 'Darwin'
SYSTEM_LINUX   = 'Linux'
SYSTEM_WINDOWS = 'Windows'


# hidden settings related
HIDDEN_SETTING_FIELD_CLI_PATH = 'cli-path'
HIDDEN_SETTING_FIELD_MEASUREMENTS = 'measurement-unit'
HIDDEN_SETTING_FIELD_SHOW_WELCOME_WARNING = 'is-welcome-warning-disabled'
HIDDEN_SETTING_FIELD_DISPLAYING_INPUT_AND_OUTPUT_BEHAVIOR = 'displaying-input-and-output-behavior'
HIDDEN_SETTING_FIELD_DISPLAY_OSM_FOR_DATAHUB = 'display-osm-for-datahub'
HIDDEN_SETTING_SAVING_PATH_FOR_DATAHUB_OUTPUTS = 'datahub-output-folder-path'
HIDDEN_SETTING_SAVING_PATH_FOR_CLI_OUTPUTS = 'cli-output-folder-path'


# GUI related
DATA_DISPLAYING_BEHAVIOUR_NON = 'off'
DATA_DISPLAYING_BEHAVIOUR_ON_FINISH = 'on-finish'
DATA_DISPLAYING_BEHAVIOUR_ON_FINISH_ONLY_OUTPUT = 'on-finish-only-output'
DATA_DISPLAYING_BEHAVIOUR_REALTIME = 'realtime'

DROPDOWN_MENU_DATA_DISPLAYING_BEHAVIOUR_NON                   = 'Do not display input & output files'
DROPDOWN_MENU_DATA_DISPLAYING_BEHAVIOUR_ON_FINISH             = 'Display input & output files'
DROPDOWN_MENU_DATA_DISPLAYING_BEHAVIOUR_ON_FINISH_ONLY_OUTPUT = 'Display only output files (i.e. classification results)'
DROPDOWN_MENU_DATA_DISPLAYING_BEHAVIOUR_REALTIME              = 'Display input & output files for each successfully processed file'

STATE_DISPLAY_OSM_FOR_DATAHUB_ON = '1'
STATE_DISPLAY_OSM_FOR_DATAHUB_OFF = '0'

TABEL_AVAILABLE_REGIONS_FIRST_COL = "Download?"
TABEL_AVAILABLE_REGIONS_SECOND_COL = "Dataset name"
TABEL_AVAILABLE_REGIONS_THIRD_COL = "Time frame"
TABEL_AVAILABLE_REGIONS_FOURTH_COL = "EPSG"
TABEL_AVAILABLE_REGIONS_FIFTH_COL = "Density"
TABEL_AVAILABLE_REGIONS_SIXTH_COL = "Total items (in current view)"
TABEL_AVAILABLE_REGIONS_SEVENTH_COL = "License"

TABEL_AVAILABLE_REGIONS_ITEMS = [
    TABEL_AVAILABLE_REGIONS_FIRST_COL,
    TABEL_AVAILABLE_REGIONS_SECOND_COL,
    TABEL_AVAILABLE_REGIONS_THIRD_COL,
    TABEL_AVAILABLE_REGIONS_FOURTH_COL,
    TABEL_AVAILABLE_REGIONS_FIFTH_COL,
    TABEL_AVAILABLE_REGIONS_SIXTH_COL,
    TABEL_AVAILABLE_REGIONS_SEVENTH_COL
]

TEXT_SIZE_INSIDE_MSG_BOX = 11
